# Generated by Django 5.2.6 on 2025-11-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayush_app', '0004_patient_created_at_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ayush_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
