# Generated by Django 5.2.6 on 2025-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayush_app', '0005_alter_patient_ayush_id_alter_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='patient',
            name='ayush_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
